### ISSUE TITLE
test project available?

### ISSUE THREAD

**Issue by manhao-chen** [sepharg/webApiAuthenticationSamples#1]
hi there,

i'm looking at your webapi authenication sample,

was wondering if you had a test project to test with

i'm currently wanting to know if i could create some webapi project with authentication

and require the client to authenticate in c# projects and javascript also

would you be able to create a test project to show how it could authenticate?

**Comment by sepharg** [comment]
Hi manhao-chen,

Thanks for writing.
Yes, I can create a test that calls the api with authentication. If you
give me 1 or 2 days I'll put it up for you

**Comment by manhao-chen** [comment]
@sepharg your a legend!

would love to see how this stuff all works at the end

**Comment by sepharg** [comment]
No worries @manhao-chen 
I've done it already, please take a look at the WebApiAuthenticationSamples.Api.Tests project
hope that's good for you 👍 Feel free to add a test for digest authentication (pull request) if you like!

**Comment by manhao-chen** [comment]
@sepharg i've just looked at the test project, 
sorry new to this webapi authorization stuff
should an hmac be implemented for security? 
i have no idea how you would implement the digest authentication :(

**Comment by sepharg** [comment]
Hi @manhao-chen 
For digest auth you would have to first do a request, and web api will return the nonce and realm.
with that, you can do another request to the same url sending the nonce, and response code

for more info on this process and the involved steps take a look at "Example with explanation" section here: 
https://en.wikipedia.org/wiki/Digest_access_authentication

**Comment by Erkin-M** [comment]
Hi @sepharg , can i ask you to help with your Digest Auth method. Do you able to add test to it, i can`t understand how it work yet. 
Thanks a lot.
P.S. Sorry for my English, not my native language

**Comment by sepharg** [comment]
Hi @soloinnet , just added the digest authentication test for you. enjoy!
