### ISSUE TITLE
Swagger page is empty

### ISSUE THREAD

**Issue by improwise** [sepharg/webApiAuthenticationSamples#2]
First of, great initiative with this!

I've noticed that the http://localhost:XXXX/swagger page seem to be always empty?

**Comment by sepharg** [comment]
Hi @improwise yeah, it seems to have been broken when I added the self hosting configuration to have the unit tests working.
I think I´ll remove it because it´s quite flaky, and instead add tests to reproduce the call to the webpage.
There´s not that many urls to access anyway
